// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PreConHub.Data;

#nullable disable

namespace PreConHub.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260223193825_AddLawFirmToApplicationUser")]
    partial class AddLawFirmToApplicationUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PreConHub.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LawFirm")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MaxProjects")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Email");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UserType");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PreConHub.Models.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserRole")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("EntityType");

                    b.HasIndex("Timestamp");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.ClosingExtensionRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OriginalClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RequestedByPurchaserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestedNewClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewedByBuilderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReviewerNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestedByPurchaserId");

                    b.HasIndex("ReviewedByBuilderId");

                    b.HasIndex("Status");

                    b.HasIndex("UnitId");

                    b.ToTable("ClosingExtensionRequests");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.Deposit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CompoundingType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConfirmedByLawyerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepositName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Holder")
                        .HasColumnType("int");

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("decimal(5,3)");

                    b.Property<bool>("IsConfirmedByLawyer")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInterestEligible")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UnitId");

                    b.ToTable("Deposits");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.DepositInterestPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualRate")
                        .HasColumnType("decimal(6,3)");

                    b.Property<int>("DepositId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepositId");

                    b.ToTable("DepositInterestPeriods");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("GoogleDriveFileId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GoogleDriveUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentType");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UnitId");

                    b.HasIndex("UploadedById");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.LawyerAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LawyerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LawyerId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UnitId", "LawyerId")
                        .IsUnique()
                        .HasFilter("[UnitId] IS NOT NULL");

                    b.ToTable("LawyerAssignments");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.LawyerNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsReadByBuilder")
                        .HasColumnType("bit");

                    b.Property<int>("LawyerAssignmentId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoteType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReadByBuilderAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LawyerAssignmentId");

                    b.ToTable("LawyerNotes");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.MortgageInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AmortizationYears")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ApprovalExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ApprovalType")
                        .HasColumnType("int");

                    b.Property<decimal?>("ApprovedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("BuilderCanViewAmount")
                        .HasColumnType("bit");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Conditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreditBureau")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CreditScore")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EstimatedFundingDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasConditions")
                        .HasColumnType("bit");

                    b.Property<bool>("HasMortgageApproval")
                        .HasColumnType("bit");

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("decimal(5,3)");

                    b.Property<bool>("IsApprovalConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBlanketMortgage")
                        .HasColumnType("bit");

                    b.Property<string>("MortgageProvider")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("PurchaserAppraisalValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnitPurchaserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UnitPurchaserId")
                        .IsUnique();

                    b.ToTable("MortgageInfos");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionText")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ActionUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RelatedUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("GroupKey");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.OccupancyFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CommonExpenseComponent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InterestComponent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PropertyTaxComponent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalMonthlyFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("OccupancyFees");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("AllowMarketingAccess")
                        .HasColumnType("bit");

                    b.Property<string>("BuilderCompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuilderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MarketingAgencyUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("MaxUnits")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("OccupancyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ProjectType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalUnits")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BuilderId");

                    b.HasIndex("MarketingAgencyUserId");

                    b.HasIndex("Status");

                    b.HasIndex("BuilderId", "Status");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.ProjectFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("AppliesToAllUnits")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConfirmedByLawyerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FeeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FeeType")
                        .HasColumnType("int");

                    b.Property<bool>("IsConfirmedByLawyer")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPercentage")
                        .HasColumnType("bit");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectFees");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.ProjectFinancials", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MarketingCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaxBuilderCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("ProfitAvailable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalInvestment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("ProjectFinancials");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.ProjectLevyCap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CapAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ExcessResponsibility")
                        .HasColumnType("int");

                    b.Property<string>("LevyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectLevyCap");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.ProjectSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ClosingProbabilityPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("DiscountPercentOfSales")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PercentAtRisk")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PercentNeedingDiscount")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PercentNeedingVTB")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PercentReadyToClose")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalDiscountRequired")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalFundNeededToClose")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalInvestmentAtRisk")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalSalesValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalShortfall")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalUnits")
                        .HasColumnType("int");

                    b.Property<int>("UnitsAtRisk")
                        .HasColumnType("int");

                    b.Property<int>("UnitsNeedingDiscount")
                        .HasColumnType("int");

                    b.Property<int>("UnitsNeedingVTB")
                        .HasColumnType("int");

                    b.Property<int>("UnitsPendingData")
                        .HasColumnType("int");

                    b.Property<int>("UnitsReadyToClose")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("ProjectSummaries");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.PurchaserFinancials", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AdditionalCashAvailable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AnnualIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Employer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EmploymentStatus")
                        .HasColumnType("int");

                    b.Property<decimal?>("ExistingMortgageBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ExistingPropertyValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ExpectedSaleDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GiftFromFamily")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("HasExistingPropertyToSell")
                        .HasColumnType("bit");

                    b.Property<string>("IncomeSource")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsPropertyListed")
                        .HasColumnType("bit");

                    b.Property<decimal?>("OtherAssetsValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherFundsAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OtherFundsDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProceedsFromSale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RRSPAvailable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalFundsAvailable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnitPurchaserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UnitPurchaserId")
                        .IsUnique();

                    b.ToTable("PurchaserFinancials");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.SOAVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BalanceDueOnClosing")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashRequiredToClose")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPurchaserCredits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalVendorCredits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<string>("UploadedFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UnitId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("SOAVersions");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.ShortfallAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AIAnalysis")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("AdditionalCashAvailable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BuilderModifiedSuggestion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DecisionAction")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("DecisionAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DecisionByBuilderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DepositsPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MortgageApproved")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MutualReleaseThreshold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("RecalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Recommendation")
                        .HasColumnType("int");

                    b.Property<string>("RecommendationReasoning")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("int");

                    b.Property<decimal>("SOAAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShortfallAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShortfallPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("SuggestedDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SuggestedVTBAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalFundsAvailable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Recommendation");

                    b.HasIndex("RiskLevel");

                    b.HasIndex("UnitId")
                        .IsUnique();

                    b.ToTable("ShortfallAnalyses");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.StatementOfAdjustments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AdditionalConsideration")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalanceDueOnClosing")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BuilderAbsorbedLevies")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("BuilderConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("BuilderCredits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CalculationVersion")
                        .HasColumnType("int");

                    b.Property<decimal>("CashBackIncentives")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashRequiredToClose")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CommonExpenseAdjustment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CommonExpensesFirstMonth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CommunityBenefitCharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConfirmedByBuilderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfirmedByLawyerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DepositInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DepositsPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DesignCredits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DevelopmentCharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EducationDevelopmentCharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ElectronicRegFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FederalHST")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FreeUpgradesValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HCRAFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HSTAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HSTRebateFederal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HSTRebateOntario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HSTRebateTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InterestOnDepositInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsConfirmedByBuilder")
                        .HasColumnType("bit");

                    b.Property<bool>("IsConfirmedByLawyer")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHSTRebateAssignedToBuilder")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHSTRebateEligible")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLawyerSOAConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<decimal>("LandTransferTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LawyerNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("LawyerSOAConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LawyerSOAConfirmedByRole")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LawyerSOAConfirmedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("LawyerUploadedBalanceDue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LegalFeesEstimate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LockedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LockerPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MortgageAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetHSTPayable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetSalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OccupancyFeesChargeable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OccupancyFeesOwing")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OccupancyFeesPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherCredits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherDebits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ParkingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ParklandLevy")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PropertyTaxAdjustment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProvincialHST")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("RecalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ReserveFundContribution")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SecurityDepositRefund")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StatusCertFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SystemBalanceDueOnClosing")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SystemCashRequiredToClose")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TarionFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TorontoLandTransferTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCredits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDebits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPurchaserCredits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalSalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalVendorCredits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TransactionLevyFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<decimal>("Upgrades")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UtilityConnectionFees")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IsConfirmedByLawyer");

                    b.HasIndex("UnitId")
                        .IsUnique();

                    b.ToTable("StatementsOfAdjustments");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.SystemFeeConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("HSTApplicable")
                        .HasColumnType("bit");

                    b.Property<bool>("HSTIncluded")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemFeeConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 170.00m,
                            DisplayName = "HCRA Regulatory Oversight Fee",
                            HSTApplicable = true,
                            HSTIncluded = false,
                            Key = "HCRA",
                            Notes = "Per unit. HST (13%) added on top at closing. Source: hcraontario.ca. Was $145 at HCRA launch (Feb 2021), increased to $170. Review annually for updates.",
                            UpdatedAt = new DateTime(2026, 2, 19, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Amount = 85.00m,
                            DisplayName = "Electronic Registration Fee (Teranet)",
                            HSTApplicable = false,
                            HSTIncluded = true,
                            Key = "ElectronicReg",
                            Notes = "Per instrument registered. Statutory fee + ELRSA fee + HST all included in flat rate. CPI-adjusted annually by Ontario government (last updated Nov 3, 2025). Source: teraview.ca.",
                            UpdatedAt = new DateTime(2026, 2, 19, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Amount = 100.00m,
                            DisplayName = "Status Certificate",
                            HSTApplicable = false,
                            HSTIncluded = true,
                            Key = "StatusCert",
                            Notes = "Regulated maximum under Ontario Condominium Act 1998 s.18(4). Tax-inclusive. Condo corporation must deliver within 10 calendar days of written request + fee payment.",
                            UpdatedAt = new DateTime(2026, 2, 19, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Amount = 65.00m,
                            DisplayName = "Transaction Levy Surcharge (LAWPRO)",
                            HSTApplicable = true,
                            HSTIncluded = false,
                            Key = "TransactionLevy",
                            Notes = "LAWPRO insurance levy. Base $65 + HST (13%) = ~$73.45 when disbursed to client. Flat province-wide rate. Source: lawpro.ca / Law Society of Ontario.",
                            UpdatedAt = new DateTime(2026, 2, 19, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PreConHub.Models.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("APSDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ActualAnnualLandTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ActualMonthlyMaintenanceFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("AppraisalDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("int");

                    b.Property<int?>("BuilderDecision")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConfirmedByLawyerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CurrentAppraisalValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("FirmClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FloorNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("HasLocker")
                        .HasColumnType("bit");

                    b.Property<bool>("HasParking")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("InterimOccupancyStartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsConfirmedByLawyer")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFirstTimeBuyer")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimaryResidence")
                        .HasColumnType("bit");

                    b.Property<bool>("LawyerConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LawyerConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LockerPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("OccupancyDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ParkingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Recommendation")
                        .HasColumnType("int");

                    b.Property<decimal>("SquareFootage")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UnitType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Recommendation");

                    b.HasIndex("Status");

                    b.HasIndex("ProjectId", "UnitNumber")
                        .IsUnique();

                    b.ToTable("Units");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.UnitFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FeeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsCredit")
                        .HasColumnType("bit");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("UnitFees");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.UnitPurchaser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPrimaryPurchaser")
                        .HasColumnType("bit");

                    b.Property<decimal>("OwnershipPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("PurchaserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PurchaserId");

                    b.HasIndex("UnitId", "PurchaserId")
                        .IsUnique();

                    b.ToTable("UnitPurchasers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PreConHub.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PreConHub.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PreConHub.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PreConHub.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PreConHub.Models.Entities.ApplicationUser", b =>
                {
                    b.HasOne("PreConHub.Models.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.ClosingExtensionRequest", b =>
                {
                    b.HasOne("PreConHub.Models.Entities.ApplicationUser", "RequestedByPurchaser")
                        .WithMany()
                        .HasForeignKey("RequestedByPurchaserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PreConHub.Models.Entities.ApplicationUser", "ReviewedByBuilder")
                        .WithMany()
                        .HasForeignKey("ReviewedByBuilderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PreConHub.Models.Entities.Unit", "Unit")
                        .WithMany("ExtensionRequests")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestedByPurchaser");

                    b.Navigation("ReviewedByBuilder");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.Deposit", b =>
                {
                    b.HasOne("PreConHub.Models.Entities.Unit", "Unit")
                        .WithMany("Deposits")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.DepositInterestPeriod", b =>
                {
                    b.HasOne("PreConHub.Models.Entities.Deposit", "Deposit")
                        .WithMany("InterestPeriods")
                        .HasForeignKey("DepositId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deposit");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.Document", b =>
                {
                    b.HasOne("PreConHub.Models.Entities.Project", "Project")
                        .WithMany("Documents")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PreConHub.Models.Entities.Unit", "Unit")
                        .WithMany("Documents")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PreConHub.Models.Entities.ApplicationUser", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Unit");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.LawyerAssignment", b =>
                {
                    b.HasOne("PreConHub.Models.Entities.ApplicationUser", "Lawyer")
                        .WithMany("LawyerAssignments")
                        .HasForeignKey("LawyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PreConHub.Models.Entities.Project", "Project")
                        .WithMany("LawyerAssignments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PreConHub.Models.Entities.Unit", "Unit")
                        .WithMany("LawyerAssignments")
                        .HasForeignKey("UnitId");

                    b.Navigation("Lawyer");

                    b.Navigation("Project");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.LawyerNote", b =>
                {
                    b.HasOne("PreConHub.Models.Entities.LawyerAssignment", "LawyerAssignment")
                        .WithMany("LawyerNotes")
                        .HasForeignKey("LawyerAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LawyerAssignment");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.MortgageInfo", b =>
                {
                    b.HasOne("PreConHub.Models.Entities.UnitPurchaser", "UnitPurchaser")
                        .WithOne("MortgageInfo")
                        .HasForeignKey("PreConHub.Models.Entities.MortgageInfo", "UnitPurchaserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnitPurchaser");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.Notification", b =>
                {
                    b.HasOne("PreConHub.Models.Entities.ApplicationUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.OccupancyFee", b =>
                {
                    b.HasOne("PreConHub.Models.Entities.Unit", "Unit")
                        .WithMany("OccupancyFees")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.Project", b =>
                {
                    b.HasOne("PreConHub.Models.Entities.ApplicationUser", "Builder")
                        .WithMany("BuilderProjects")
                        .HasForeignKey("BuilderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PreConHub.Models.Entities.ApplicationUser", "MarketingAgencyUser")
                        .WithMany()
                        .HasForeignKey("MarketingAgencyUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Builder");

                    b.Navigation("MarketingAgencyUser");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.ProjectFee", b =>
                {
                    b.HasOne("PreConHub.Models.Entities.Project", "Project")
                        .WithMany("Fees")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.ProjectFinancials", b =>
                {
                    b.HasOne("PreConHub.Models.Entities.Project", "Project")
                        .WithOne("Financials")
                        .HasForeignKey("PreConHub.Models.Entities.ProjectFinancials", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.ProjectLevyCap", b =>
                {
                    b.HasOne("PreConHub.Models.Entities.Project", "Project")
                        .WithMany("LevyCaps")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.ProjectSummary", b =>
                {
                    b.HasOne("PreConHub.Models.Entities.Project", "Project")
                        .WithOne()
                        .HasForeignKey("PreConHub.Models.Entities.ProjectSummary", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.PurchaserFinancials", b =>
                {
                    b.HasOne("PreConHub.Models.Entities.UnitPurchaser", "UnitPurchaser")
                        .WithOne("Financials")
                        .HasForeignKey("PreConHub.Models.Entities.PurchaserFinancials", "UnitPurchaserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnitPurchaser");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.SOAVersion", b =>
                {
                    b.HasOne("PreConHub.Models.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PreConHub.Models.Entities.Unit", "Unit")
                        .WithMany("SOAVersions")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.ShortfallAnalysis", b =>
                {
                    b.HasOne("PreConHub.Models.Entities.Unit", "Unit")
                        .WithOne("ShortfallAnalysis")
                        .HasForeignKey("PreConHub.Models.Entities.ShortfallAnalysis", "UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.StatementOfAdjustments", b =>
                {
                    b.HasOne("PreConHub.Models.Entities.Unit", "Unit")
                        .WithOne("SOA")
                        .HasForeignKey("PreConHub.Models.Entities.StatementOfAdjustments", "UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.Unit", b =>
                {
                    b.HasOne("PreConHub.Models.Entities.Project", "Project")
                        .WithMany("Units")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.UnitFee", b =>
                {
                    b.HasOne("PreConHub.Models.Entities.Unit", "Unit")
                        .WithMany("Fees")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.UnitPurchaser", b =>
                {
                    b.HasOne("PreConHub.Models.Entities.ApplicationUser", "Purchaser")
                        .WithMany("PurchaserUnits")
                        .HasForeignKey("PurchaserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PreConHub.Models.Entities.Unit", "Unit")
                        .WithMany("Purchasers")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Purchaser");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.ApplicationUser", b =>
                {
                    b.Navigation("BuilderProjects");

                    b.Navigation("LawyerAssignments");

                    b.Navigation("Notifications");

                    b.Navigation("PurchaserUnits");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.Deposit", b =>
                {
                    b.Navigation("InterestPeriods");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.LawyerAssignment", b =>
                {
                    b.Navigation("LawyerNotes");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.Project", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Fees");

                    b.Navigation("Financials");

                    b.Navigation("LawyerAssignments");

                    b.Navigation("LevyCaps");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.Unit", b =>
                {
                    b.Navigation("Deposits");

                    b.Navigation("Documents");

                    b.Navigation("ExtensionRequests");

                    b.Navigation("Fees");

                    b.Navigation("LawyerAssignments");

                    b.Navigation("OccupancyFees");

                    b.Navigation("Purchasers");

                    b.Navigation("SOA");

                    b.Navigation("SOAVersions");

                    b.Navigation("ShortfallAnalysis");
                });

            modelBuilder.Entity("PreConHub.Models.Entities.UnitPurchaser", b =>
                {
                    b.Navigation("Financials");

                    b.Navigation("MortgageInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
